config/routes.rb
Rails.application.routes.draw do
  root to: "requests#index"

  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :requests, only: [:index, :show, :create] do
    member do
      patch :assign
      patch :solve
    end
    resources :comments, only: :create
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :request

  validates :content, :user, :request, presence: true

  # Scopes..............
  scope :order_by_creation, -> { order(created_at: :desc) }

end

app/models/customer.rb
class Customer < User
  has_many :requests, dependent: :nullify
end

app/models/request.rb
class Request < ApplicationRecord
  enum status: [:pending, :solved]

  validates :subject, :content, :customer, presence: true
  belongs_to :customer
  belongs_to :support_agent
  has_many :comments, dependent: :destroy

end

app/models/support_agent.rb
class SupportAgent < User
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :requests, dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  TYPES = %w(Customer Admin SupportAgent)

  validates :type, presence: true
  validates :type, inclusion: { in: TYPES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def not_found_json(resource)
    render json: { alert: t('not_found', resource: resource) }, status: :not_found
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_request, only: :create

  def create
    comment = @request.comments.build(permitted_params.merge({ user_id: current_user.id }))
    if comment.save
      render json: { name: current_user.name, content: comment.content }, status: :ok
    else
      render json: { message: 'Failed' }, status: :unprocessable_entity
    end
  end

  private
  def load_request
    @request = Request.find_by(id: params[:request_id])
    not_found_json 'Request' unless @request
    if current_user.type == 'Customer'
      @request = Request.find_by(id: params[:request_id], customer_id: current_user.id)
    else
      @request = Request.find_by(id: params[:request_id])
    end
    not_found_json 'Request' unless @request
  end

  def permitted_params
    params.permit(:content, :request_id, :user_id)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_requests, only: :index
  before_action :initialize_request, only: :index
  before_action :allow_customer, only: :create
  before_action :load_request, only: [:show, :assign, :solve]
  before_action :allow_support_agent, only: :assign

  def index
  end

  def new
  end

  def show
  end

  def create
    @request = Request.new(permitted_params_for_create.merge(customer_id: current_user.id))
    if @request.save
      flash[:notice] = 'Request Submitted successfully.'
    else
      flash[:alert] = @request.errors.full_messages.to_sentence
    end
    redirect_to requests_path
  end

  def assign
    if @request.update(support_agent_id: current_user.id)
      flash[:notice] = 'Request assigned successfully'
    else
      flash[:alert] = @request.errors.full_messages.to_sentence
    end
    redirect_to request_path(@request)
  end

  def solve
    if @request.update(status: 'solved')
      flash[:notice] = 'Request solved successfully'
    else
      flash[:alert] = @request.errors.full_messages.to_sentence
    end
    redirect_to request_path(@request)
  end

  private

  def initialize_request
    @request = Request.new
  end

  def permitted_params_for_create
    params.require(:request).permit(:subject, :content)
  end

  def load_request
    if current_user.type == 'Customer'
      @request = Request.find_by(id: params[:id], customer_id: current_user.id)
    else
      @request = Request.find_by(id: params[:id])
    end
    return if @request
    flash[:alert] = 'Request not found'
    redirect_to requests_path
  end

  def load_requests
    if current_user.type == 'Customer'
      @requests = current_user.requests.order(:created_at)
    else
      @requests = Request.all.order(:created_at)
    end
  end

  def allow_customer
    return if current_user.type == 'Customer'
    flash[:alert] = 'Unauthorized'
    redirect_to requests_path
  end

  def allow_support_agent
    return if current_user.type == 'SupportAgent'
    flash[:alert] = 'Unauthorized'
    redirect_to requests_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RequestsHandler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :header %>
  </head>

  <body>
    <nav class="navbar navbar-default nav-main-header">
      <div class="container-fluid">
        <% if current_user.present? %>
          <div class="navbar-header">
            <a class="navbar-brand navbar-link request-header-link" href="<%= requests_path %>">Requests</a>
          </div>
        <% end %>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.present? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="color:white;" href="#">
                Hi <%= current_user.name %><span class="caret"></span>
              </a>
              <ul class="dropdown-menu dropdown-menu-right" role="menu">
                <li role="presentation"><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
            <% else %>
            <li role="presentation"><a href="" style="color:white;">Sign in</a></li>
            <li role="presentation"><a href="" style="color:white;">Sign up</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class='mar-top-60'>
      <% if notice.present? || alert.present? %>
      <div class="alert alert-dismissible fade in <%= notice.present? ? 'alert-success' : 'alert-danger' %>" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <span class="message"><%= notice || alert %></span>
      </div>
      <% end %>
    </div>
    <div class='container'>
      <%= yield %>
    </div>
    <%= yield :body_bottom %>
  </body>
</html>

app/views/requests/_new_request_modal.html.erb
<%= stylesheet_link_tag 'requests/new' %>

<div class="modal fade" id="newRequest" tabindex="-1" role="dialog" aria-labelledby="newRequest" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">New Request</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@request) do |f| %>
          <div class="form-group">
            <%= f.label :subject %>
            <%= f.text_field :subject %>
          </div>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<%= stylesheet_link_tag 'requests/index' %>

<div class="bs-example" data-example-id="simple-table">
  <div class="heading clearfix">
    <p class="pull-left request-list" ><h4><b>Requests List</b></h4></p>
    <% if current_user.type == 'Customer' %>
      <%= link_to 'Create New Request', "#", class: "btn btn-default pull-right", data: { toggle: "modal", target: "#newRequest" } %>
    <% end %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Subject</th>
        <th>Status</th>
        <th>Support Agent</th>
        <th>Raised At</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @requests.each do |request| %>
      <tr>
        <td><%= request.subject %></td>
        <td><%= request.status %></td>
        <td><%= request.support_agent.try(:email) %></td>
        <td><%= request.created_at %></td>
        <td><%= link_to 'View', request_path(request) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'new_request_modal' %>

app/views/requests/show.html.erb
<% content_for :header do -%>
  <%= stylesheet_link_tag 'requests/show' %>
<% end -%>

<div class="request-title fix-pos clearfix">
  <div class="pull-left">
   <h4> <b>Request Details</b> </h4>
  </div>
  <div class="pull-right">
    <div class="action-btns">
      <% if current_user.type == 'SupportAgent' %>
        <a href="<%= assign_request_path(@request) %>" class="btn btn-info btn-approve" data-method="patch">ASSIGN TO ME</a>
      <% end %>
      <% unless @request.status == 'solved' %>
        <a href="<%= solve_request_path(@request) %>" class="btn btn-info btn-approve" data-method="patch">MARK AS SOLVED</a>
      <% end %>
    </div>
  </div>
</div>
<div class='request-container'>
  <h3>Subject: <%= @request.subject %></h3>
  <h4>Content: <%= @request.content %></h4>
  <div class="comment-div" id="tab-1">
    <div id='flash-div' style='display:none;' class="alert alert-danger alert-dismissable" style="margin-bottom:0;">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
      <strong>Error!</strong> Comment could not be successfully submitted. Please try again
    </div>
    <% unless @request.status == 'solved' %>
      <div class="row comment-box" id='form-comment-div'>
        <div class="col-lg-11 col-md-8">
          <h4 class="user-name"><%= current_user.name %></h4>
          <div class="comment-text">
            <%= form_tag request_comments_path(@request), method: 'post' do %>
            <%= text_area_tag :content, nil, rows: 3, placeholder: 'Type your comment here' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <hr>
    <h4>Comments</h4>
    <% @request.comments.order_by_creation.each do |comment| %>
    <div class="row comment-box">
      <div class="col-lg-11 col-md-8">
        <h4 class="user-name"><%= comment.user.name %></h4>
        <p class="comment-time"><%= distance_of_time_in_words(Time.now, comment.created_at) %> ago</p>
        <div class="comment-text"><%= comment.content %></div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% content_for :body_bottom do -%>
  <%= javascript_include_tag 'comment' %>
<% end -%>